### ISSUE TITLE
CLI context in cwait run don't use cowait.yml

### ISSUE THREAD

**Issue by emilwareus** [backtick-se/cowait#165]
When I run 

`cowait run --cluster CLUSTER TASK`

CLUSTER is not properly read from the cowait.yml file. I am trying to configure docker-network to access a db from a separate service, but the cluster configurations are not properly read from the cowait.yml file. 

I'm using workdir when building

cowait.yml
``` 
version: 1
cowait:
  image: my/image
  clusters:
    docker:
      type: docker
      network: my-network
```

**Comment by johanhenriksson** [comment]
Might be a documentation fail 😅

The cluster configuration has been moved to a global configuration file in the users  home directory: `~/.cowait.yml`

Try this:

```yml
default_cluster: docker
clusters:
  docker:
    type: docker
    network: my-network
```
