### ISSUE TITLE
Deploy command configuration

### ISSUE THREAD

**Issue by johanhenriksson** [backtick-se/cowait#335]
The `deploy` command would be much more useful if it could be configured from the yaml, similar to how `docker-compse` works. 

Running `cowait deploy` without arguments should deploy/update all the defined deployments. `cowait deploy <deployment name>` deploys/updates a specific task.

Example:
```yaml
version: 1
cowait:
  deploy:
    my-deployed-task:
      task: cowait.tasks.shell
      inputs:
        cmd: "ls -l"
      environment:
        DB_PASS:
          source: secret
          name: db-secret
          key: password
```
