### ISSUE TITLE
Local Volume Mount support

### ISSUE THREAD

**Issue by johanhenriksson** [backtick-se/cowait#52]
Create basic support for local volume mounts, preferably extendable to more general persistent storage solutions later on.

```yaml
# pipeline.yml
version: 1
pipeline:
  # ...
  volumes:
  - type: bind
     src: logs
     dst: /var/logs
```
