### ISSUE TITLE
Global Context

### ISSUE THREAD

**Issue by johanhenriksson** [backtick-se/cowait#53]
Clusters etc should be configured on a per-user basis.

Example global configuration:
```yaml
clusters:
  # local docker configuration:
  docker:
    network: tasks
  
  # local (kubeconfig) kubernetes config
  kubernetes:
    namespace: default

  # example api cluster
  dev:
    type: api
    endpoint: http://dev.c.backtick.se
    username: johanh
    password: omfgdope
```

Then, to run a task on the `dev` cluster:
```bash
$ pipeline run lazy --provider dev
```
